[package]
name = "trans-master"
version = "0.1.0"
authors = ["zuowenjian <zuowenjian@outlook.com>"]

[dependencies]
rand = "0.3.14"
http = "0.1.4"
curl = "0.4.11"
json = "0.11.13"
file = "*"
[[bin]]
name = "trans-master" 
path = "src/main.rs"
